### ISSUE TITLE
Small issue with day 1 exercise 03

### ISSUE THREAD

**Issue by zhmurov** [ENCCS/sycl-workshop#3]
In exercise 03, the device properties (memory etc) for CPU are arbitrary large values. Not a big deal, but probably worth mentioning in the exercise description.

**Comment by robertodr** [comment]
It could be a bug in hipSYCL. I've tried on a different machine and it also return nonsense values for the OpenMP platform.

**Comment by robertodr** [comment]
This is still happening with hipSYCL v0.9.2

**Comment by robertodr** [comment]
I need to add a note in the content section that this is expected in hipSYCL and nothing to worry about.

**Comment by illuhad** [comment]
hipSYCL does not report arbitrary large values, but in some cases `std::numeric_limits<T>::max()`. Generally this can mean one of two things:
- A property is unlimited on a particular device/backend (e.g., no real maximum allocation size on most host operating systems due to modern virtual memory implementations with first-touch allocation policy)
- hipSYCL does not know the result, e.g. because the query does not apply or make sense to the backend, or the backend cannot provide this information.

**Comment by robertodr** [comment]
@illuhad thanks for clearing this up. I've incorporated your explanation in the text #17
